---
- name: Install SNMP
  hosts:
    - web1
    - db1
    - branch-client
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install snmp
      apt:
        name: snmp
        state: present

    - name: Install snmpd
      apt:
        name: snmpd
        state: present

    - name: Start snmpd service
      service:
        name: snmpd
        state: started
        enabled: yes
